### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by saxobroko** [dyelax/encore.ai#12]
Can i have a tutorial on what files to open and where or how to compile it through visual studio or something? anything? just a tutorial...?

**Comment by dyelax** [comment]
Hi @saxobroko, there are instructions for how to run the code in the README, under "Instructions to Train". Let me know if you have any specific questions or if those don't work. (Note that I think you'll have to be on TensorFlow v0.12 to run this)

**Comment by saxobroko** [comment]
yea that doesnt tell me what files to open or anything..
