### ISSUE TITLE
Generating test data

### ISSUE THREAD

**Issue by stevenhurwitt** [dyelax/encore.ai#6]
I'm a little confused about generating test data with the code. So far it seems that Tensorflow saves a meta, index and data file related to the checkpoint file, while the github instructions say to just feed in the checkpoint file for test data once the model is trained.

From searching the web it looks like we have to use the meta file and use something like:
saver = tf.train.import_meta_graph('/tmp/model.ckpt.meta')
    saver.restore(sess, "/tmp/model.ckpt")

To get the model up and running again. However looking at the code it looks like the new data is almost generated probabilistically?

My only guess is that something like this line above may be used in one of the "state" lines in the Generate function (in the LSTM model file), although that doesn't seem quite right (not exactly sure what these lines do specifically).

If anyone can help me with this I'd really appreciate it, I feel like I'm really close to making the code work :(

**Comment by stevenhurwitt** [comment]
nevermind I actually got it work somehow but I don't know what exactly I did. If anyone else is reading this and having the same issue let me know and I can send you my code or something, running it now with more steps to make sure it still works & (hopefully) get better results.

**Comment by dyelax** [comment]
Hey Steven,

The TensorFlow save/restore syntax has changed since I wrote this. I'll update it in the code and the usage instructions when I have a chance to make sure everything works on 1.0!

**Comment by haroldstephan** [comment]
Hi Steven, I am at the stage you were at when you wrote this post. Could you please share with me the code you used in place of <ckpt_file> to read the model from the: meta, index and data files

python runner.py -a <artist_name> -l ../save/models/<model_save_name>/<ckpt_file> -t

Thank you in advance, Harold

**Comment by GsHeri** [comment]
i'm at the same point too...
